### ISSUE TITLE
【BUG】掉帧甚至卡退

### ISSUE THREAD

**Issue by rencc1379** [cliff1o/publicresource#10]
视线人一多FPS就掉得厉害，开夜视仪更卡，然后中途还出现过一次卡住不动然后游戏闪退的情况。

**Comment by cliff1o** [comment]
加入了2個優化
-20人以上隱藏 P 模組 
-加回了 /invis ,  可大約透過隱藏玩家提升 FPS

**Comment by cliff1o** [comment]
tested by admin
