### ISSUE TITLE
【建议】群众反映神化模式出场概率过高，希望减少神化的出场概率

### ISSUE THREAD

**Issue by 1132904601** [cliff1o/publicresource#124]
王的移动性能太高有的王很爱跳来跳去瞄准都很累。打完收益也不高，大家都抱怨不喜欢打神化王。希望能调低出现的概率。现在的概率有时候甚至连续两场都是神化模式

**Comment by 1132904601** [comment]
帮代填单 你迷人的笑颜建议:神化模式25人以上开启

**Comment by cliff1o** [comment]
神化因為 在特殊中佔比太多,  如 神化有 4個模式 .  戰力 ,變異 (2個)    對比下出現機率較高
後續會增加不是神化模式的模式來平衡 出現機率 
暫不修改
![3730cd3c56e4700e4f813596c1328851](https://github.com/cliff1o/publicresource/assets/90167089/1cb85afb-5062-40b5-867d-cff092be8ab5)
