### ISSUE TITLE
準雷改同奪魂長刃一齊用有問題

### ISSUE THREAD

**Issue by XENOOO4** [cliff1o/publicresource#125]
開槍時會有揮刀聲，如果有人係前面會有斬中人嘅聲
貼面用準雷改打boss會變左長刃個傷害
未知普通準雷or V1有冇同樣問題

**Comment by cliff1o** [comment]
暫時未能測試出來 請列出可以 重現問題的 step

**Comment by XENOOO4** [comment]
我快速選擇係揀係主武準雷改，小刀奪魂長刃

**Comment by XENOOO4** [comment]
每當開槍時，就會有長刃個下左鍵聲
如果開槍時我前面有其他人類，會有一下長刃斬中人嘅聲
貼面打boss會變左長刃左鍵傷害

**Comment by cliff1o** [comment]
手動 換一次槍 , 換一次刀,  還有沒有問題

**Comment by XENOOO4** [comment]
Same

**Comment by cliff1o** [comment]
交給核心檢查 , 還是無法測試

**Comment by siunam321** [comment]
刀聲:

https://github.com/cliff1o/publicresource/assets/104430134/1cc9a7df-baab-4fd6-96c6-3982eec07c64

**Comment by siunam321** [comment]
另外準雷改的狙鏡是原本的狙鏡:

![image](https://github.com/cliff1o/publicresource/assets/104430134/cf6007e5-5486-4431-9fb6-5ff8ae2475ff)

**Comment by cliff1o** [comment]
進行了第一版修正
再測試下

**Comment by cliff1o** [comment]
有問題再重開本貼
