### ISSUE TITLE
【建议】把中毒减伤减速这个技能 下放到低难度魔王

### ISSUE THREAD

**Issue by 1132904601** [cliff1o/publicresource#126]
代上不去GitHub的人填单 大意如题

**Comment by cliff1o** [comment]
下放到那一個難度 ? 
難度低了 對 新手玩家會造成不小負面影響  , 以本來傷害不高, 受到影響會更低 
加上一堆debuff  容易被殺 
 (如何解決)

**Comment by cliff1o** [comment]
暫時關閉,  有回應再重開
