### ISSUE TITLE
【建议】优化活动点获取方式

### ISSUE THREAD

**Issue by KBKKKK66** [cliff1o/publicresource#127]
这么说一个问题吧。肝一天下来活动点是50-60不等 但是排行榜一至榜三一天不止60活动点 这才十天别人就获取了500点 普通肝一点不上榜的十天差不多 200-300左右。
建议：1.如果活动点是作为一个月的目标建议限制榜一至榜三获取活动点的限制每天只能获取多少 不然你一月的东西几天就出来了然后别人还在往死里肝
2.或者吧活动点作为任务每月每天固定的也行毕竟活动点你是作为一个月的时间或者更长的时间走的 不是一两天就能换了最高突破书或者其他东西。
我说的就这些希望kdg看到了 想想吧

**Comment by cliff1o** [comment]
https://github.com/cliff1o/publicresource/issues/128
