### ISSUE TITLE
【建议】pt点获取方式增加

### ISSUE THREAD

**Issue by Miyuuuko** [cliff1o/publicresource#128]
500pt换一个突破，上不了榜1小时5点，100个小时一个月，每天都要玩3个小时，而且是存活，那必须要3个小时以上，真的不是每个人都有那么多时间玩魔王的，你之前说能换到大部分奖励，普通人真的很难做到，连一本突破都难。我建议是每日任务每个1pt点，每周任务每个2pt点，一个月完成全部任务我算下来总共能拿494pt左右，也就换一本突破书，其他攒的可以换些别的什么的。

**Comment by cliff1o** [comment]
改動如下

每日任務完成10個後 可獲 5 pts
每周任務完成 10 後 可獲 15 pts
回合再按傷害tier結算 pts 

TOP 1 100%
TOP 2 50
TOP 3 30%
TOP 4-10% 10%
TOP 10 - 20  5 %
TOP 20 後, 1 %
