### ISSUE TITLE
【bug/建议】az新手奖励

### ISSUE THREAD

**Issue by Tonylemon19** [cliff1o/publicresource#130]
![image](https://github.com/cliff1o/publicresource/assets/54575597/b405f6b7-8576-4cbd-8cad-e71bba1c2439)
已知新手奖励X7 7天，但存在每20级送随机枪械12小时的福利
因此在拥有时限X7奖励的情况下领取新手奖励会导致7天的福利无效，有没有考虑过这个时长可以叠上去？

**Comment by cliff1o** [comment]
deployed
