### ISSUE TITLE
【bug】az新手助攻概率不生效

### ISSUE THREAD

**Issue by Tonylemon19** [cliff1o/publicresource#131]
![image](https://github.com/cliff1o/publicresource/assets/54575597/2bf70b9c-9005-4ec7-9397-8d2ade319bd7)
![image](https://github.com/cliff1o/publicresource/assets/54575597/9bc8fdce-3dae-4bff-a816-aee844667278)
用的两个账号，第一个全中文，第二个纯英文名
经测试得只有小概率获得助攻奖励，但我使用大号就能全吃助攻。bug出现原因未知待查

**Comment by cliff1o** [comment]
你有沒有用槍打? 
是不是VIP

**Comment by Tonylemon19** [comment]
两个非vip全新号，有使用枪械击杀僵尸。多次重进问题依旧，获得助攻奖励仍为概率事件
使用大号时即使不进行任何攻击仍能获取所有助攻奖励，推测问题与vip有关

**Comment by cliff1o** [comment]
要用槍械打 目標 最小一槍,  先會有助攻,  而助攻會延伸一定次數 到 同一目標 (例如 我打了1 槍 A,  A死了 Y 次, Y 次其間我也計助攻)
VIP 有沒有攻擊也保底 50%
