### ISSUE TITLE
嚴重問題 幽能.M32.AT4.英雄戰擊榴砲模式.(不確定武器 玩具奇兵的飛彈模式) 原因：神化模式

### ISSUE THREAD

**Issue by xkoalaxasukax** [cliff1o/publicresource#133]
我那2場AT4貼身炸問題都來自於 神化雷克斯結束後概率會出現你說的AT4.幽能.M32變成貼身炸問題 觸發條件不知道 但確定是神化雷克斯結束後的問題

我不確定觸發貼身炸的問題原因是否因為 技能：吸星大法 此技能關係使用後因為其他人使用砲彈這些武器導致武器數據錯誤 神化Dr.Rex回合結束後 使用此砲彈那些武器全都被判定開火後有物體擋住導致立馬炸這些判定錯誤問題 搞到這些武器變成當小刀來用的武器做使用

**Comment by cliff1o** [comment]
請再測試,  做了一次優化 
但我懷疑不是REX 相關

吸星大法的技能無法影響  object 
設定上non solid

**Comment by xkoalaxasukax** [comment]
新增不確定問題 神化雙子節結束後(雙子勝利) 下局對抗模式不知道有沒有人使用標題上武器 結束後(人˙類勝利)下局逃亡模式 我使用AT4 又進入我說明的情況 然後這場也有人說他的幽能也是這情況 所以不知道是神化雙子模式問題還是其他問題

**Comment by xkoalaxasukax** [comment]
![20240612221019_1](https://github.com/cliff1o/publicresource/assets/170393732/669cfe52-61b2-4c20-9b61-fd0741d13f89)
先傳這個 不知道會不會是這個殘留關係導致的bug

**Comment by Krystal879** [comment]
这个问题只有打完神化模式才会出现，是不是因为神化模式的问题

**Comment by xkoalaxasukax** [comment]
> 這個問題只有打完神化模式才會出現，是不是因為神化模式的問題

是，因為之前我遇到時候都是神化DR.REX時候結束 下回合會這樣但KDG說不是DR.REX問題 所以再觀察一下 現在就神化模式問題偏高 但觸發點不明 還要再查

**Comment by Krystal879** [comment]
目前根据我的观察，只有神化模式被清场以后出现，如果人类胜利没有出现这个BUG，且一天一次很奇怪

**Comment by cliff1o** [comment]
未能發現問題原因
要求更多資訊

**Comment by xkoalaxasukax** [comment]
盡量找出原因，這個觸發方式還沒找到

**Comment by cliff1o** [comment]
fixed in 1.5
