### ISSUE TITLE
【BUG】龙炮改近距离二段伤害消失

### ISSUE THREAD

**Issue by Miyuuuko** [cliff1o/publicresource#14]
龙炮改在近距离有时候只能打出一段伤害（不切枪情况），有时候要等一会二段伤害才跳出来，切枪切快的话100%没有二段伤害，如果单单为一个二段伤害进行慢切的话输出频率还没有普通龙炮高，后面可能还会被反超

**Comment by cliff1o** [comment]
問題:近距离是指槍械好近魔王? 
射地下有無2段傷
龍炮現在只有範圍傷, 槍械準心在什麼位置也不會再有槍傷

**Comment by Miyuuuko** [comment]
> 問題:近距离是指槍械好近魔王? 射地下有無2段傷 龍炮現在只有範圍傷， 槍械準心在什麼位置也不會再有槍傷

有1-2人距离。射地下有时候有2段，但是也要等一会才能出伤害，有时候没有二段伤害。是龙炮改的二段龙头发射，和准心枪伤无关。

**Comment by cliff1o** [comment]
測試服未能測到以效果,  是撞了人模?

**Comment by achris12369** [comment]
我也有這問題 你切槍太快就會沒二段傷害

**Comment by Miyuuuko** [comment]
> 測試服未能測到以效果, 是撞了人模?

没有，我都是往魔王地上打

**Comment by cliff1o** [comment]
本機服未能測試出 , 懷疑和FPS 等有關 
因龍炮再無準心傷害, 建意地上打

暫無法修正
