### ISSUE TITLE
【BUG】SVDEX 惡夢及挑戰模式沒有傷害加成

### ISSUE THREAD

**Issue by siunam321** [cliff1o/publicresource#140]
![image](https://github.com/cliff1o/publicresource/assets/104430134/26f09bba-18b3-445c-898d-6bae7caa4504)

**Comment by cliff1o** [comment]
![image](https://github.com/cliff1o/publicresource/assets/90167089/d6ae0bb3-6f2f-4ddd-818a-0c409b933d06)

**Comment by cliff1o** [comment]
可再測試
