### ISSUE TITLE
【BUG】魔王技能"波動攻擊"強化無效

### ISSUE THREAD

**Issue by siunam321** [cliff1o/publicresource#142]
Same as #91 

![image](https://github.com/cliff1o/publicresource/assets/104430134/56079be1-9546-4b60-b78c-4915a29de65c)

![image](https://github.com/cliff1o/publicresource/assets/104430134/f1a09fe3-c5da-46cc-ae43-d2e0aad06efb)

**Comment by cliff1o** [comment]
顯示問題, 己修正
