### ISSUE TITLE
希望能完善一下人物皮肤的查看

### ISSUE THREAD

**Issue by Normannst** [cliff1o/publicresource#145]
萌新想看看游戏里所有的人物皮肤都长啥样 能显示游戏里模型就行了 好去对着一个去肝

**Comment by Normannst** [comment]
![Uploading QQ截图20240612002255.png…]()

**Comment by cliff1o** [comment]
Engine 問題 , 不能在遊戲中提供人物檢視, 可查看

【腾讯文档】CS1.6 Legend 魔王百科
https://docs.qq.com/sheet/DTGh1UHJsRVhmWVlB?tab=BB08J2
