### ISSUE TITLE
【BUG】SVDEX bugs

### ISSUE THREAD

**Issue by siunam321** [cliff1o/publicresource#147]
現有傷害加成，但：
1. 沒有左鍵cvar (`svd_dmg_a`)
2. 左鍵打神化王射1發=2發子彈 (#112)
3. Cannon 只有5發 (正常有10發)
4. Cannon 1發=2炮
5. Cannon 開火後右下HUD 沒扣子彈
6. Cannon 開火後有物體擋住導致立馬炸

**Comment by cliff1o** [comment]
1, 3, 4, 5, fixed 
6 正常
2 研究中
