### ISSUE TITLE
［建议］AZ T皮掉落问题

### ISSUE THREAD

**Issue by Tonylemon19** [cliff1o/publicresource#149]
已知一套基础套需要12个T皮，并且T王只会出现在难度1
先不讨论皮的掉落概率，单从玩家的战力和经验需求来说基本上就很难会有玩家会反复刷难度1
因此有没有考虑让T王能在其他更高的难度里刷新？例如难度5~7或者更高？

**Comment by cliff1o** [comment]
己在無限模式 10 增加T王出現
