### ISSUE TITLE
離子改和破壞者價值不平𧗾

### ISSUE THREAD

**Issue by sadcc** [cliff1o/publicresource#156]
離子改 1排彈+激光 30000
破壞者  1排彈+爆炸 45000
破壞者射2排彈 離子先射到一排
Dps 上限 完全不同一個水平
未計破壞者係神化用到同遠近攻都得
離子神化=0 激光0 同樣1500g
老的槍是否冇人權？

**Comment by cliff1o** [comment]
離子 成長值較高 
可比較50 級下的離子和破壞者分別
