### ISSUE TITLE
【BUG】SVDEX 用職業"生存型"技能"精密射擊"傷害異常

### ISSUE THREAD

**Issue by siunam321** [cliff1o/publicresource#157]
用"精密射擊"前爆頭傷害是`4800`, 用了之後**除了外爆頭**是`6000`

https://github.com/cliff1o/publicresource/assets/104430134/52e19510-6e02-4f10-afa5-50641cb9f733

**Comment by cliff1o** [comment]
正常應該係?

**Comment by cliff1o** [comment]
SVD 爆頭比例是有調整過

**Comment by siunam321** [comment]
正常是`4800`

**Comment by cliff1o** [comment]
精密射擊 是爆頭修正是 0.5 
而英雄槍 是 0.4 
所以精密射擊對一些槍是會提高
