### ISSUE TITLE
CS1.6 殭屍對抗BUG

### ISSUE THREAD

**Issue by a123909636** [cliff1o/publicresource#161]
![image](https://github.com/cliff1o/publicresource/assets/152900260/14fbba26-e17f-44dc-93e6-bce9862b03e8)

技能商店 購買了10%傷害 結果我再次購買 不會疊加 也沒說明說只能買一次..
至少寫插件寫一下只能購買一次的說明 或者 再次購買寫已經購買過了吧...
結果多買一次

ID:Aeiou-cow

**Comment by cliff1o** [comment]
fixed

**Comment by a123909636** [comment]
> 固定的

沒有多買 扣了SP了沒有補償嗎?

**Comment by a123909636** [comment]
> 固定的

多買扣了SP了沒有補償嗎？
