### ISSUE TITLE
【BUG】人物技能"機槍傷害增加 10%" 無效

### ISSUE THREAD

**Issue by siunam321** [cliff1o/publicresource#162]
槍: Crow-7

使用前 (爆頭):
![image](https://github.com/cliff1o/publicresource/assets/104430134/09bbe1cd-81a9-4b62-a8d0-650fca018137)

使用後 (爆頭):
![image](https://github.com/cliff1o/publicresource/assets/104430134/40f5a8cb-9404-40c4-96f8-84ff0ae1daaa)

**Comment by cliff1o** [comment]
fixed
