### ISSUE TITLE
ZS嚴重BUG

### ISSUE THREAD

**Issue by PekoraOuO** [cliff1o/publicresource#163]
可以切換為觀戰視角通關，觸發條件未知，需求人數2以上，會像病毒般傳染，正常視角的碰到觀戰的也會變觀戰視角。
![Uploading QQ图片20240617031730.jpg…]()

**Comment by PekoraOuO** [comment]
![QQ图片20240617031730](https://github.com/cliff1o/publicresource/assets/161242499/ddfede73-acb2-4efe-b53b-d278164ac8c5)

**Comment by cliff1o** [comment]
fixed
