### ISSUE TITLE
【疑问】AZ猛男职业

### ISSUE THREAD

**Issue by Tonylemon19** [cliff1o/publicresource#166]
![image](https://github.com/cliff1o/publicresource/assets/54575597/ae96a7a9-282e-4d4a-ba24-1ce9a7e215d7)
已知猛男职业如图，在击杀僵尸会hp自动回复到1500血的问题后
那么这个增加体力的被动作用是什么？
实测每个回合开始时血量都是一样的400

**Comment by cliff1o** [comment]
回合開始時 增加 200 血
