### ISSUE TITLE
【BUG】SVDEX 惡夢 2/2 沒有傷害加成

### ISSUE THREAD

**Issue by siunam321** [cliff1o/publicresource#168]
底傷: `3000`

惡夢**1/2** 爆頭傷害`6000`:

![image](https://github.com/cliff1o/publicresource/assets/104430134/cdc35c6f-7548-4dc3-9cfa-ae8764df685e)

惡夢**2/2** 爆頭傷害`4800`:

![image](https://github.com/cliff1o/publicresource/assets/104430134/8d05a7c9-53cd-4a0d-a1ea-b4b5c99346a3)

**Comment by cliff1o** [comment]
fixed
