### ISSUE TITLE
【建議】增加快速選槍欄位，BOSS服現有只有三個能設定 

### ISSUE THREAD

**Issue by 016kevin** [cliff1o/publicresource#173]

**Comment by cliff1o** [comment]
快速選槍欄位 accept 
增加烈魔者右鍵爆炸範圍且提升20%傷害 reject
BOSS服商店販售SP版的15分槍械經驗卡，一張3000~5000SP?  Reject
以前副武器有個榴彈手炮，能不能加回來 accept

**Comment by cliff1o** [comment]
榴彈手炮 會在1.5 期間加回
