### ISSUE TITLE
【建议】职业差距过大，某些职业根本无人问津，大多数人都是生存型/肌肉型

### ISSUE THREAD

**Issue by 1132904601** [cliff1o/publicresource#175]
因现有职业太过不平衡，大多数人都是选择其中一两种,尤其是生存型和肌肉型。所以我帮忙提供了新的职业效果（一转），仅供参考。
我认为重新设计后的职业效果更具倾向性,百花齐放，不会让所有人都无脑选择同一个职业。
当前版本职热门度 肌肉型>生存型>灵活型>运动型=特异型

1.新手型不变

**2.生存型 倾向步枪 综合性**
**[主动]精密射击** [X]秒内造成的伤害全判定为爆头  _(不改)_
**[被动]吸收伤害** 造成一定伤害会回复生命值(上限150)   _(改为升级提高上限)_                  
**[被动]精准爆头** 爆头时额外附加[x]点伤害  _(提高爆头收益)_

**3.运动型 倾向霰弹枪 冲锋枪 近距离**
**[主动]冲锋** 向前方跳跃一段距离  _(紧急后跳的反向版本，爆发性移动技能，在紧急时刻非常好用)_
**[被动]长跑者** 移动时受到的伤害减少[X] _(提高玩家的生存能力用)_
**[被动]挑战者** 附近[X]米存在敌人时，获得[1.25]伤害加成 _(鼓励近战枪械高风险高回报的技能)_

**4.肌肉型 倾向机枪 弹容大类型**
**[主动]伤害爆发** [X]秒内伤害1.25倍 _(不改)_
**[被动]耐力惊人** 携带机枪时移动速度提高[X%] _(减免一下机枪带来的减速)_
**[被动]火力压制** 每连续开枪[x]次后，伤害提高[1.1]，最高叠加3次 停止射击时重置效果 _(鼓励大容量枪械进行持续火力输出)_

**5.灵活型 倾向刀 近战**
**[主动]隐身** 隐身[X]秒 冷却时间[X]秒 _(改为冷却型技能，因为玩刀的隐身根本不够用)_
**[被动]呼吸回血** 每移动[X]米回复[X]生命 _(为刀类玩家增加续航能力 刀目前太容易死)_                
**[被动]致命一击** 近战攻击有[X%]概率造成双倍伤害 _(相当于刀当中的爆头，鼓励高风险高回报)_

**6.特异型 倾向远距离武器 单次伤害高的武器**
**[主动]传送** 传送至随机一名队友位置  _(狙击手最好的保命方式)_                                
**[被动]子弹附魔** 距离魔王越远，伤害加成越高 最高[X%]   _(鼓励远距离输出)_                
**[被动]超能一击** 每隔[X]秒，下一次枪械攻击造成双倍伤害  _(倾向单次伤害高但频率低的武器)_

**Comment by wdf250** [comment]
灵活真要改那样的话得限制只能用带副武器，不然是我的话就算不玩刀也选这个，因为隐身真的很实用

**Comment by 1132904601** [comment]
> 灵活真要改那样的话得限制只能用带副武器，不然是我的话就算不玩刀也选这个，因为隐身真的很实用

冷却长点就没事，需要投资很多技能点才能达到理想冷却

**Comment by 1132904601** [comment]
二转职业的平衡问题更大，90%的玩家都是选择复仇者。
以下仅供参考，我设计思路是一转是倾向枪械，二转是倾向技巧玩法

**1.独奏者 综合 条件苛刻**
**[主动]演奏乐章** 无视判定条件，直接触发[独狼][自给自足]持续[X]秒  _(一个短暂无视条件爆发的机会)_
**[被动]独狼** 当附近[X]米以内小于[3]个人类时，+20%攻 +20%速 +30%伤害抵抗 _(当前版本可以无限复活，这样改更合理)_
**[被动]自给自足** 当场上人类数量低于[50%] 开火时有[x]概率不消耗子弹 _(当前版本可以无限复活，这样改更合理)_

**2.潜行者 暗杀 偷袭 倾向近战**
**[主动]高阶隐身** 长时间隐身[X]秒 _(一个超长时间的隐身)_
**[被动]潜行** 静步移动时，人物会慢慢透明 _(提高近战玩家的生存能力)_
**[被动]背刺** 在敌人背后近战攻攻击额外增加[1.25]倍伤害 _(提高近战武器的风险与回报)_

**3.挑战者 高风险 高操作 倾向爆头**
**[主动]背水一战** [X]秒内生命值降为1，移动速度下降，但攻击[1.5]倍 _(不改)_
**[被动]猎头者** 爆头伤害[1.2]倍，非爆头伤害[0.7]倍 _(提高上限 降低下限 这是一个高手职业)_
**[被动]穿颅一击** 爆头击中[5]次时回复[1]生命 _(提高生存续航)_

**4.复仇者 快速复活 后期 长盘 适合新手**
**[被动]意志** 每复活[1]次，增加[X%]伤害抵抗 _(提高复活后收益)_
**[被动]愤怒** 每复活[1]次，增加[X%]攻击力 _(提高复活后收益)_
**[被动]亡者归来** 减少[X]秒复活时间 _(加快复活时间，提高玩家体验，觉得复活太慢的自己投资技能点)_

**5.祝福者 爆炸伤害 非子弹枪 看运气**
**[主动]天雷** 获得[X]秒的无限手雷补给 _(不需要好枪就可以短暂爆发输出一会儿)_
**[被动]随机轰炸** 爆炸伤害随机获得[1.5]与[0.6]倍攻击 _(随机看脸)_
**[被动]再来一次** 爆炸伤害有[X]概率额外造成一次爆炸 _(随机看脸)_

**6.超能者 主打特效伤害 高频率伤害**
**[主动]魔法弹匣** 获得[X]秒的无限弹药 _(短暂爆发)_
**[被动]烈焰子弹** 每发射[X]发子弹，额外发射1枚烈焰子弹造成[X]伤害 _(可以花费大额技能点投资伤害，不需要很好的枪可能打出理想伤害)_
**[被动]心灵感应** 可以预知魔王的冷却时间_(预知带的技能感觉比较鸡肋，预知冷却会更好)_
