### ISSUE TITLE
枪械箱问题

### ISSUE THREAD

**Issue by Funnyqun** [cliff1o/publicresource#176]
之前只抽一种枪械的时候已经有抽数了，改成枪械箱之后也只能继续抽了。
现在出了一把怒海狂鲨，实战下来不太满意，首先是霰弹枪，离远了几乎没有输出能力，无法穿人需要近距离输出，魔王近身时右键的定身和击退效果不大，使用时生存压力大。
对比起20G的爆炎蒸汽，保底1500G的怒海狂鲨，在实战中不论是输出环境还是输出伤害都没有明显提升，个人认为不值这个价位。
个人建议是能出个换购系统，可以直接换购低于此枪械G数的枪械，或者加G换购同价位的枪械。

**Comment by cliff1o** [comment]
爆炎蒸汽因設置錯誤變為了普通槍, 而不是時限槍,    不可和普通的槍做對比 
核心測試 怒海狂鲨 威力是合理 .

另一個問題 
https://github.com/cliff1o/publicresource/issues/16
