### ISSUE TITLE
[BUG] MK3維京不能充能

### ISSUE THREAD

**Issue by BOSSPING** [cliff1o/publicresource#179]
我發現一些地圖MK3是不能充能，例如一些地圖打在地上或牆上沒有彈窿的話，MK3空槍也不能充能！
而且，打BOSS MK3係穿透子彈，穿過BOSS打上牆上冇彈窿都係冇充能。
可能今日試新圖，新圖開始都充唔到能量或者MK3本身BUG左！

呢啲只係我自己發現，未必係啱!
如果係因為以上原因，希望可以將所有地圖都牆，地，建築都變實心！
辛苦晒！

**Comment by L1mmmm** [comment]
不太可能，工程量大。Nam：结账加班费费

**Comment by siunam321** [comment]
確認是地圖問題 (clip texture)，以下新版本的地圖可能已修正該bug:
- boss_30000hp_v2
- boss_cry_fix_v3
- boss_ilove4PPPP_v3
- boss_kdg_pro_v4
- zm_Funny_Moments_v2

**Comment by siunam321** [comment]
> 確認是地圖問題 (clip texture)，以下新版本的地圖可能已修正該bug:
> 
>     * boss_30000hp_v2
> 
>     * boss_cry_fix_v3
> 
>     * boss_ilove4PPPP_v3
> 
>     * boss_kdg_pro_v4
> 
>     * zm_Funny_Moments_v2

移除clip texture 後還是沒有修正，懷疑是`func_wall` 問題

**Comment by siunam321** [comment]
確認是`func_wall` 問題，以下新版本的地圖已修正該bug:
- boss_30000hp_v3
- boss_ilove4PPPP_v4
- zm_Funny_Moments_v3

*boss_cry_fix_v3* 沒有使用`func_wall` 所以不需要修改
