### ISSUE TITLE
建議 優化LD模式

### ISSUE THREAD

**Issue by xkoalaxasukax** [cliff1o/publicresource#183]
因為由於很多人抱怨說LD倒光後，魔王進入一刀秒狀態 覺得魔王過於強勢導致玩家反抗魔王的成功率大幅降低很多 甚至想換圖找一個適合的地圖用

推薦方案：
方案1：LD全倒光 魔王進入一刀秒狀態 全員撐30秒到1分鐘後自動挑選下一位LD登場(僅限1位) 一刀秒模式變會正常模式，如LD再倒 全員降速20%+降火力 為原本火力傷害(沒有LD在場提升傷害加成) 魔王不進入一刀秒狀態好讓魔王有追擊機會+玩家們想辦法擺脫魔王追擊並且不會因為魔王一刀秒狀態而導致放棄抵抗魔王的機會。但怕這樣指令會不會出錯？
方案2：LD全倒光 魔王不進入一刀秒狀態，魔王減速.僵持抗性提升至50到75% 讓魔王不要瘋狂被僵持和瘋狂緩速 可讓魔王有更好追擊的發揮機會

**Comment by xkoalaxasukax** [comment]
新增建議 魔王勝利條件可追加 擊倒3個LD即可將全員團滅，多給玩家保護LD參與感(也可以不要，怕其他玩家體感不佳)

**Comment by cliff1o** [comment]
暫時LD 下降為 普通 2/2  , 其他暫時不變 ,   直到1.6 再決定
