### ISSUE TITLE
建議 更改挑戰異變王難度以上投票通過率(暫時)

### ISSUE THREAD

**Issue by xkoalaxasukax** [cliff1o/publicresource#187]
投票挑戰率調成75%到90%即可挑戰好了，倒時候下版本更新後調成50%投票通過率再來看 挑戰失敗就調回75%以上挑戰率(挑戰期間為3天 如果異變王可以打過就不調高投票挑戰率)

**Comment by cliff1o** [comment]
己下掉變異挑戰 , 挑戰暫時所見能打
