### ISSUE TITLE
建議sp 槍

### ISSUE THREAD

**Issue by Pokala-12** [cliff1o/publicresource#189]
目前來說sp 槍完全沒有吸引人的地方，除了離子，但是離子需要40萬sp，不可能拿著比較低階強度的槍打到40萬sp吧，所以比較希望準雷這種中間強度的槍可以調降價格，（特槍卡一樣無法使用），要不然每天上線就是打完每日就下線，完全不會去想要存sp ，因為gash 都比sp 好存了。

建議
準雷價格調降，準雷以前的15萬sp 就很足夠了。

**Comment by cliff1o** [comment]
1.5 調整 SKULL-5  到 100000 , 準雷到 200000
