### ISSUE TITLE
【BUG】SVDEX cannon allows reloading

### ISSUE THREAD

**Issue by siunam321** [cliff1o/publicresource#19]
# Steps to Reproduce
1. SVDEX right click to activate cannon mode
2. Launch 1 cannon, current cannon ammo should be `9`
3. Hold "R" to reload, or type `+reload` in console
4. Cannon ammo should return back to `10`

**Comment by siunam321** [comment]
Btw same as normal mode, ammo will return back to `30`

**Comment by cliff1o** [comment]
set_entvar( pItem, var_grenade, get_entvar( pItem, var_grenade ) - 1); <--  missing var_grenade
