### ISSUE TITLE
ZS月Rank計算BOSS不增加

### ISSUE THREAD

**Issue by PekoraOuO** [cliff1o/publicresource#191]
6/17~6/23 我已經刷超過至少10個以上的zsboss，但排行還是維持在5
![Screenshot_20240624-174101](https://github.com/cliff1o/publicresource/assets/161242499/58c07c82-1294-41a3-8a6c-a407ff701812)

**Comment by xkoalaxasukax** [comment]
這個我是不知道他是忘記弄還是什麼情況了...

**Comment by xkoalaxasukax** [comment]
你打的 BOSS計算是打這些地圖嗎 sub-boss是大胖
zs_trace_lg
zs_nightmare_lg(難度3/6開始~6/6結束)
zs_lastclue_lg
zs_deadend_lg

**Comment by xkoalaxasukax** [comment]
順便說 我那個紀錄是上個月的 沒刷新

**Comment by PekoraOuO** [comment]
當然是刷zs圖尾王za圖沒有boss可以刷吧，大胖我也知道是sub-boss，而且主要就是因為沒計算boss不然我應該早就第一了才對..
