### ISSUE TITLE
【BUG】Invalid command `cl_filterstuffcmd`

### ISSUE THREAD

**Issue by siunam321** [cliff1o/publicresource#192]
懷疑是newline (`\n`) 問題

![image](https://github.com/cliff1o/publicresource/assets/104430134/a7811ccf-9406-411d-91c7-48aee5027b48)

**Comment by cliff1o** [comment]
![image](https://github.com/cliff1o/publicresource/assets/90167089/c2e5f1b7-7c72-4ab7-8616-eff0e5eb34e0)
沒有\n ,  估計會拿下了
