### ISSUE TITLE
【建议】每日任务枪械次数多加一个达到多少[伤害]完成

### ISSUE THREAD

**Issue by 1132904601** [cliff1o/publicresource#193]
代L1m填单，多加一个条件。例如机枪任务要么击中1000次，要么造成20W伤害，达成任意一个条件就可以完成任务。
因为现在按照击中次数算，个别枪开枪频率很低次数很难打。例如[机枪]AT4。[冲锋枪]龙炮等

**Comment by cliff1o** [comment]
暫不考慮, 可使用其他槍械代打
