### ISSUE TITLE
惡夢難度加強

### ISSUE THREAD

**Issue by Pokala-12** [cliff1o/publicresource#194]
我也蠻想建議惡夢難度加強，每次當到惡夢1/2 技能都不實用，無敵cd 又要很久（2/2因為有昇龍波所以看起來還好，但是還是偏弱）根本沒有惡夢的感覺，就是被人類被追著打，感覺都是殭屍服了，現在都感覺當到boss就是很衰，少了一場賺sp的時間

目前只能建議惡夢1/2，有中毒跟無敵調回555

**Comment by cliff1o** [comment]
deployed in 1.5
