### ISSUE TITLE
【bug】AZ boss能量积攒问题

### ISSUE THREAD

**Issue by Tonylemon19** [cliff1o/publicresource#199]
由先前提供的信息得知boss受到攻击时会增加`min(5,damage*0.0035)`能量
因此可知当M134秒杀僵尸时会出现：影子在短时间内多次攻击boss导致boss reload异常，以致boss在短时间内连续放出多个技能

https://github.com/cliff1o/publicresource/assets/54575597/9ac72c81-e0c8-43bb-a4ad-6be02599b96d

**Comment by cliff1o** [comment]
pending fix in 1.4
