### ISSUE TITLE
【BUG】戰令-鬼泣死士，打王沒傷害 & 武器經驗  & 快速換彈的功能不見

### ISSUE THREAD

**Issue by Sora977** [cliff1o/publicresource#2]
戰令-鬼泣死士打王的時候都是 0 傷害，且沒有武器經驗
還有武器快速換彈的功能不見了

![Half Life Screenshot 2024 05 19 - 13 31 27 55](https://github.com/cliff1o/publicresource/assets/87259269/003868c8-bacf-4632-be55-a2c5f2c6eebd)

**Comment by cliff1o** [comment]
#define DAMAGE <int> issue
fix attemp 1 

快速補彈要求:
先按住R鍵,  黃條到達點時放開R 鍵 , 即可快速補彈
