### ISSUE TITLE
【bug】AZ背包扩充问题

### ISSUE THREAD

**Issue by Tonylemon19** [cliff1o/publicresource#203]
![image](https://github.com/cliff1o/publicresource/assets/54575597/ce75e375-2596-41dc-bbb8-4269d67afa2d)
如图，扩充购买至25次时无法打开背包

**Comment by Tonylemon19** [comment]
由测试可知 当购买到21/10开始无法打开背包

**Comment by cliff1o** [comment]
正常只能買 10個 , 但超出了上限所以BUG

**Comment by cliff1o** [comment]
擴充object 60 到80
