### ISSUE TITLE
重置職業後隱藏能力消失

### ISSUE THREAD

**Issue by Melilth** [cliff1o/publicresource#204]
![e69360e6-1181-498b-9ab0-128654c06741](https://github.com/cliff1o/publicresource/assets/174325896/a7a07a96-fd6b-45b2-bff7-d2887775ef47)
![9936d347-78a8-40e0-93b0-ea9b994befb2](https://github.com/cliff1o/publicresource/assets/174325896/a10523ee-d458-4095-8f15-9c0a4ed4d3f1)

**Comment by siunam321** [comment]
fixed
