### ISSUE TITLE
【BUG】换图之后Gash丢失

### ISSUE THREAD

**Issue by yyyangc** [cliff1o/publicresource#21]
ID：柊 做了两天每日任务10+10g 每日在线5+4g 领取了200级和400级奖励 疑似400等级奖励丢失了且不能重新领取 目前只剩下了54g
以下是管理发的log日志 
锦木千束 20:17:37
L 05/20/2024 - 19:40:46: 名稱: 柊 Gash: 74 (Disconnect Gash)

锦木千束 20:17:43
L 05/20/2024 - 19:40:55: 名稱: 柊 等級: 1 經驗: 0/100 點數: 0 Gash: 0 兌換卷: 0 活動點數: 0 帶領點數: 0 (Level Up)

锦木千束 20:17:49
L 05/20/2024 - 19:41:03: 名稱: 柊 Gash: 44 (Disconnect Gash)

**Comment by yyyangc** [comment]
补充一下 再次换图之前是55g 后重新进服又变成了54 算上丢失的400级奖励应该是有84g

**Comment by cliff1o** [comment]
測試修正,  如幾天沒有相關回報.  就當己解決
