### ISSUE TITLE
建議 龍炮改傷害問題

### ISSUE THREAD

**Issue by 0001411** [cliff1o/publicresource#216]
單王傷害不及20萬SP準雷 雙王傷害又輸同價位破壞者 根本用唔到都無理由要用呢把槍
建議傷害改一改

**Comment by 0001411** [comment]
單王甚至連2萬sp20gash果把衝鋒槍都不如 傷害同1500gash不成正比

**Comment by cliff1o** [comment]
請提升 槍械等級傷害
龍炮成長值極高
