### ISSUE TITLE
bg11-改 bug and 合成永久概率有问题

### ISSUE THREAD

**Issue by Furina1234** [cliff1o/publicresource#217]
1.bg11-改除了右键最大充能子弹为5 其余伤害 快速补单==均和普通bg11 一致
2.合成台 合成概率每次合成永久概率说是要+10？，实际合成一次永久概率+1？
3.主线任务每日一签bug 签到数字不会变化，每日一枪会随着每天使用 任务数字变少。

**Comment by Furina1234** [comment]
![合成概率](https://github.com/cliff1o/publicresource/assets/174613029/6bfc857a-b2db-47c0-beb8-f427404f8cf4)

**Comment by Furina1234** [comment]
![Uploading 10%.jpg…]()

**Comment by Furina1234** [comment]
![Uploading 日常.png…]()

**Comment by Furina1234** [comment]
![Image_1720009072156](https://github.com/cliff1o/publicresource/assets/174613029/2abbaadc-261c-447f-be5b-946aa5b792f1)
![Image_1720009064229](https://github.com/cliff1o/publicresource/assets/174613029/25d67461-f150-4795-9422-0b6ca5f86d90)

**Comment by Furina1234** [comment]
补单bug

**Comment by Furina1234** [comment]
https://github.com/cliff1o/publicresource/assets/174613029/2a8af45e-4ba1-4cea-a0ec-3bc2fc0083ad

补单bug

**Comment by cliff1o** [comment]
修正機率問題, 和補彈問題
