### ISSUE TITLE
未修正問題

### ISSUE THREAD

**Issue by xkoalaxasukax** [cliff1o/publicresource#219]
#133 

https://github.com/cliff1o/publicresource/assets/170393732/32edd97c-498d-4ada-bece-1a6ac636ed5e

神化 雙子結束後(人類生存勝利) 後續出現的

**Comment by cliff1o** [comment]
只有特定地圖出現問題?

**Comment by xkoalaxasukax** [comment]
> 只有特定地圖出現問題？

不確定，可能是 近期地圖已經大量限制神化模式了 如果要推測會有這問題 要從1.4版本開始加入的地圖一個一個看 1.4前加入的地圖沒遇到過

**Comment by cliff1o** [comment]
前天做了一次修正,  如果問題沒有持續
就可以關閉問題
