### ISSUE TITLE
boss主线任务每日一签bug

### ISSUE THREAD

**Issue by Furina1234** [cliff1o/publicresource#220]
主线任务 每日一签 不知是bug还是需要签到7天之后才能完成，
签到不会加任务进度 ，同每日一枪每次使用会扣除进度 。
![日常](https://github.com/cliff1o/publicresource/assets/174613029/75d59fa4-abac-4814-b545-eb8cf54cbfa8)

**Comment by cliff1o** [comment]
扣除進度唔係正常?  每日一簽fixed
