### ISSUE TITLE
龍炮右鍵失效

### ISSUE THREAD

**Issue by huaige0420** [cliff1o/publicresource#221]
如題

**Comment by cliff1o** [comment]
龍炮邊到有右鍵?

**Comment by siunam321** [comment]
龍炮改第二段攻擊?

**Comment by cliff1o** [comment]
咁點樣為止失效

**Comment by siunam321** [comment]
![image](https://github.com/cliff1o/publicresource/assets/104430134/9ed4084d-a8e4-4463-8eb9-146ce95df424)

**Comment by cliff1o** [comment]
佢理解錯,  左鍵自帶龍頭 唔洗右鍵
