### ISSUE TITLE
【建议】关于离子改的经验

### ISSUE THREAD

**Issue by Miyuuuko** [cliff1o/publicresource#223]
龙炮和雷神   1级+100攻，每级1000经验，为什么离子改1级+25攻也是每级1000经验，之前说的按照龙炮和雷神的百分比改那也应该是每级250经验吧，你要实在说离子每次发射2发子弹，那500经验吧，怎么会也是1000经验？不合理

**Comment by cliff1o** [comment]
合理,  DPS計 离子成長值和 龙炮和雷神 差不多
