### ISSUE TITLE
【BUG】挑戰王的變異瞬閃會卡牆或卡地面

### ISSUE THREAD

**Issue by Sora977** [cliff1o/publicresource#23]
![Half Life Screenshot 2024 05 20 - 22 33 01 50](https://github.com/cliff1o/publicresource/assets/87259269/a80378d8-bbec-425e-98d2-43db4bb5d922)

![Half Life Screenshot 2024 05 20 - 22 33 04 54](https://github.com/cliff1o/publicresource/assets/87259269/f0013c45-c5d7-4129-ba8b-57f456e30333)

**Comment by cliff1o** [comment]
角度優化 (+ v_angle判定) , 另外加入解卡守尾門 . 

	new Float:vOrigin[3], Float:vAngle[3], Float:vForward[3], Float:vRight[3], Float:vUp[3]
	
	pev(id, pev_origin, vOrigin)
	pev(id, pev_view_ofs,vUp) //for player
	xs_vec_add(vOrigin,vUp,vOrigin)
	pev(id, pev_v_angle, vAngle) // if normal entity ,use pev_angles
	
	angle_vector(vAngle,ANGLEVECTOR_FORWARD,vForward) //or use EngFunc_AngleVectors
	angle_vector(vAngle,ANGLEVECTOR_RIGHT,vRight)
	angle_vector(vAngle,ANGLEVECTOR_UP,vUp)
	
	origin[0] = aimoriign[0] + vForward[0] * -30.5 + vRight[0] * -30.5 + vUp[0] * -36.0
	origin[1] = aimoriign[1] + vForward[1] * -30.5 + vRight[1] * -30.5 + vUp[1] * -36.0
	origin[2] = aimoriign[2] + vForward[2] * -30.5 + vRight[2] * -30.5 + vUp[2] * -36.0

	if(aimoriign[2] - vOrigin[2] < 0) // aim down
	origin[2] += 36.0
