### ISSUE TITLE
BS 加農砲槍械等候提升 ， 但傷害幾乎沒有提升

### ISSUE THREAD

**Issue by GoTwo123** [cliff1o/publicresource#230]
０等的加農砲傷害 和３０等的加農砲傷害幾乎相同 有顯示ＡＴＫ ＋ ６

**Comment by cliff1o** [comment]
加特林由 每級+0.2 上調為 每級 + 0.6 攻 
注, 加特林計法是 傷害 X 7  (7發子彈)
