### ISSUE TITLE
【BUG】任务击杀5只挑战boss 疑似不计算

### ISSUE THREAD

**Issue by yyyangc** [cliff1o/publicresource#239]
总计杀了4只boss 有两次为特效杀死 两次为子弹杀死 任务不显示已击杀次数

**Comment by yyyangc** [comment]
【弑神者】击杀5只神化王任务也一样 击杀后不计算

**Comment by cliff1o** [comment]
修正版己放入服內, 要求測試

**Comment by cliff1o** [comment]
https://github.com/cliff1o/publicresource/issues/282
