### ISSUE TITLE
【BUG】Nemesis模式，王有機率無法移動會卡在原地

### ISSUE THREAD

**Issue by Sora977** [cliff1o/publicresource#24]
![Half Life Screenshot 2024 05 20 - 21 05 15 59](https://github.com/cliff1o/publicresource/assets/87259269/16af10df-4c4f-46a0-98c6-a62dc7e5e06e)

**Comment by cliff1o** [comment]
神化前要求空礦位置並且不要蹲下. 否則容易出問題
