### ISSUE TITLE
建議暑假活動改良

### ISSUE THREAD

**Issue by tomchoi524** [cliff1o/publicresource#248]
![23242A3116E46D6E0576C1059ED11597](https://github.com/user-attachments/assets/447508b5-32cd-482e-9621-50e39a73cb9f)
箱子X及西瓜掉穫太低 沒有玩家會想打足一個暑期換來一把超特槍三天 所以提議提高跌落率及穫取方法 或是有保底的方式

一個活動要睇目標同成效 已經有一個換換活動要肝點數 平均一個月先換到一個1.1傷害 其他嘢根本換唔到 係付出同收穫唔成正比 有幾多個人真係可以由開服打到熄服  

依家嘅暑期活動 你要人哋嘅付出一模一樣都係要肝嘅話 根本個目標就重疊咗 我覺得暑期活動可以改一改 當係比玩家體驗武器 反正佢哋換到再多嘅禮物 最多都係三日超神器 如果向住呢個方向行就應該諗個活動係期望人攞到獎勵 就算換晒都唔怕 而唔係機率低到千辛萬苦 隨時成個暑假先換到一把超特槍3日

簡單啲黎講就係 邊有人為咗三日超特槍 同你肝足成個暑假 如果每把我都可以玩到三日 其實成效 server唔會損失咗啲咩 但係玩家嘅角度睇 佢得到嘅唔少喎 雖然三日真係唔多 但係槍威力 sp exp係佢哋得到嘅野 付出同收穫會成正比 仲可以唔使貧富懸殊 課長玩哂 其他人玩都冇得玩 鎖起哂啲野添

我用換換活動以下張相嚟舉個例 收穫同付出唔成正比 有幾多個人真係可以換到1.1傷害,突破卡,人物 如果我玩得再辛苦都係換唔到嘅話 咁放上去做獎品嘅意義係咩 根本都唔係想人攞到嘅 所以建議調低門檻 以送比人為前提 希望所有人都拎得到及拎得多 提高人流 如果唔係個點數根本就唔重要 因為根本都冇可能攞到禮物 如果你將啲獲取方法易啲 目標係派禮物咁派 期望佢哋得到多啲嘢 呢個方向會唔會好啲？

我嘅睇法係咁活動道具給得少  跟沒給冇分別 唔啱聽嘅當我廢噏都得 啱聽嘅可以一齊諗吓 活動道具可以比得多 但之後會有回收/刪掉
以目標係派禮物咁派 期望佢哋得到多啲嘢為前提

**Comment by PekoraOuO** [comment]
我認同這些建議，其實講直接點課長會直接定制不會想著刷這些，因為我就是這種心態，不然我也沒必要搞定制武器，這種t系列武器本來就是該給普通玩家玩的頂級神器，西瓜我建議是一個箱子必出1~5個隨機抽，再送原本該有的獎勵才會有真正暑期活動獎勵的感覺
