### ISSUE TITLE
【建议】LD和异变模式开回噩梦

### ISSUE THREAD

**Issue by yyyangc** [cliff1o/publicresource#249]
强制回2/2实际血量还是噩梦的量 尤其是LD模式 botLD和不会玩的LD太多导致游戏体验很差 90%的对局都是时间到了人类打不过 BS抓不完又退回1/2  不如开放超特还能让大多数人玩的爽一些

**Comment by zdghrh7** [comment]
同意 LD模式現在常常發生BOT LD的情況 基本上發生就是等輸
然後人類無限復活 純屬拖時間當沙包
此外常常爆發完時間還有7-8分鐘 純屬坐牢 導致只要到了LD模式跟變異模式基本上人流全部跑光了
變異模式則是強制鎖定2/2 但BS的血量不拿超特槍完全打不動
基本上就是人類躲貓貓
