### ISSUE TITLE
【BUG】神化安格拉變身後問題

### ISSUE THREAD

**Issue by terryCheungz** [cliff1o/publicresource#252]
![2E3E213B-8BAE-436D-B6B9-7CB806527CAC](https://github.com/user-attachments/assets/59942863-0891-4143-bd87-26dd880cdcaa)

1. 畫面會版被Frame Attack (x.x/200.0)覆蓋原先魔王Reload數值
2. 左鍵(普攻)hit range問題, 現在幾乎要貼面才能造成傷害
3. 體型問題導致現今一部份地圖變身後會出現上圖情況(畫面顯示出界外完全看不到地圖內)

**Comment by cliff1o** [comment]
1 fixed 
2 frame 只計touch , 沒有範圍攻
3. 使用ctrl 下降
