### ISSUE TITLE
【BUG】复仇者职业技能愤怒伤害异常

### ISSUE THREAD

**Issue by 1132904601** [cliff1o/publicresource#256]
![没点愤怒](https://github.com/user-attachments/assets/057a7df9-450b-4fcc-84a8-04b3a26e2edc)
没点愤怒 凖雷改
![点了愤怒](https://github.com/user-attachments/assets/95c3d151-d80e-43ec-9b36-260beef3171f)
点愤怒 凖雷改
实际效果是直接+1.00倍

**Comment by cliff1o** [comment]
fixed
