### ISSUE TITLE
【建議】營運&提高建議獎勵

### ISSUE THREAD

**Issue by terryCheungz** [cliff1o/publicresource#270]
1. 有鑑於部份玩家不能進入github, 建議可以讓管理員/核心代填. 代填時加上提出者的CS ID讓提出者之後能取得獎勵. 亦因應早幾天出現魔王卡BUG沒有管理員/核心在場, 建議可招募少量管理員(+幫手填單)

2. 提高建議獎勵. 獎勵要遠比BUG回報高吸引不同玩家提議. 合理者可獲獎勵(例: 50 GASH, 100 GASH, etc) [可以由此ticket開始 A_A]

3. 方便獎勵顯示及核心發放獎勵, 建議GIT新增兩個label (reward, received(?)). reward用作建議 ticket時當合理時加上(可領獎與否由KDG判斷), 核心容易知道是否合資格發放獎勵(提出者同樣看到reward就找核心領獎). 至於BUG ticket亦可加reward, 提出者看到reward並測試後向核心領獎. 另外新增received label讓核心知道此ticket之前領獎與否亦避免重複領獎情況, 發放獎勵後由該核心加received label

**Comment by cliff1o** [comment]
1, 3 同意
2 不同意
