### ISSUE TITLE
【BUG】生存职业技能问题

### ISSUE THREAD

**Issue by yyyangc** [cliff1o/publicresource#271]
![1](https://github.com/user-attachments/assets/c9ec3567-99ff-4908-a3dc-965f25818a2b)
![2](https://github.com/user-attachments/assets/54843cd7-05c2-4f7e-9d6f-f23364da90ff)
![3](https://github.com/user-attachments/assets/a97788be-e5d3-40d1-b0b7-2e7a01454bfe)
使用技能精密射击时效果正常生效 技能结束后爆头伤害异常
图1加了该技能 图2未加技能

**Comment by 1132904601** [comment]
![精华爆头未点](https://github.com/user-attachments/assets/9f0d6f2b-d0bc-4f2d-a21c-25c0f62ac69b)
未点精准爆头
![精华爆头点了后](https://github.com/user-attachments/assets/427652c3-b55c-4096-b414-38d8f6a1a592)
点了精准爆头

**Comment by cliff1o** [comment]
爆頭是分開一個系統, 好像是更變本攻 , 和加成無關
己測試有效果
