### ISSUE TITLE
【建议】暑假活动的箱子

### ISSUE THREAD

**Issue by 1X6440** [cliff1o/publicresource#281]
建议把保底箱子调快一些，或者掉率的几率调高一些。今晚玩了6 7个小时就开了五个箱子，三个保底两个掉落。这么肝了都只能开五个箱子，那些没什么时间玩的人基本也就一天两个或者一个。后面的奖励大部分都拿不到。希望能改善一些

**Comment by cliff1o** [comment]
保底改為 1.5掉獲
提高 普通箱出現機率
