### ISSUE TITLE
【BUG】人物技能 步枪伤害10% 无效果

### ISSUE THREAD

**Issue by 1132904601** [cliff1o/publicresource#295]
![步枪OFF](https://github.com/user-attachments/assets/0367af23-d554-4e2b-b318-2746229362b2)
枪械 爆能脉冲 未使用步枪10%
![步枪ON](https://github.com/user-attachments/assets/355477e6-5500-4401-bb28-d165ea1b04e0)
枪械 爆能脉冲 使用步枪10%
加成无变化

**Comment by cliff1o** [comment]
要求測試
