### ISSUE TITLE
【BUG】戰令-獵殺夜行，打王沒武器經驗 & 快速換彈的功能不見

### ISSUE THREAD

**Issue by Sora977** [cliff1o/publicresource#3]
戰令-鬼泣死士打王的時候沒有武器經驗，
還有武器快速換彈的功能不見了

![Half Life Screenshot 2024 05 19 - 13 24 44 04](https://github.com/cliff1o/publicresource/assets/87259269/1392f817-4499-436f-a2bc-84d51c102a7f)

**Comment by cliff1o** [comment]
![image](https://github.com/cliff1o/publicresource/assets/90167089/d8b62d48-0207-4ee3-a036-e9968d44619c)
fix attemp 1
reapply PlayerOldWeapon . 

		if (get_weapon_type(PlayerOldWeapon[attacker]) != WPN_TYPE_OTHER)
		{
			PlayerGunXp[attacker][PlayerWeapon[attacker]] += gunxp
			GlobalMaxGunXp[attacker] += gunxp;
			if(GlobalMaxGunXp[attacker] >= getglobalgunlevelxp(attacker))
			GlobalMaxGunXp[attacker] = getglobalgunlevelxp(attacker);
		}
