### ISSUE TITLE
boss  职业bug

### ISSUE THREAD

**Issue by Furina1234** [cliff1o/publicresource#308]
同#309 使用ak潘多拉右键可以击杀队友
昨天以为是职业问题
今天实测是枪问题。

**Comment by Furina1234** [comment]
> 祝福者职业第一个技能 概率发射飞弹 那个飞弹会杀队友（不清楚是不是概率 但是死后视角会锁在队友且右上角不会弹是谁击杀的。）
最新发现 死三次 同一个人使用的是ak潘多拉右键

**Comment by cliff1o** [comment]
唔明
