### ISSUE TITLE
【BUG】T1 對BUG 傷害異常?

### ISSUE THREAD

**Issue by cliff1o** [cliff1o/publicresource#32]

**Comment by siunam321** [comment]
https://github.com/cliff1o/publicresource/assets/104430134/0bf03bcd-00b7-4179-99ed-45d20940617a

**Comment by siunam321** [comment]
好似得呢隻進化咗嘅王先有, model phys 問題?

**Comment by cliff1o** [comment]
有人回報BOT 10倍傷害 , 己針對BOT傷害調低10 倍
