### ISSUE TITLE
【BUG】保护时间内会死亡

### ISSUE THREAD

**Issue by 1132904601** [cliff1o/publicresource#321]
测试应该是显示的保护时间与实际不符合，实际保护时间已经结束了，但是UI还是提示在保护时间
![保护时间内死亡](https://github.com/user-attachments/assets/1310531e-bdf1-4485-8c6a-abc02daacae8)

**Comment by cliff1o** [comment]
不是BUG,  CS 的 print idle 時間問題 ,  己加入刷新一條 print
