### ISSUE TITLE
bos 建议 枪口火焰问题

### ISSUE THREAD

**Issue by Furina1234** [cliff1o/publicresource#327]
如题 野牛枪口火焰过于巨大 晃眼 
希望优化下
![Image_1725371407191](https://github.com/user-attachments/assets/9dc35ee6-3cf0-4880-8a70-b1e454e84550)

**Comment by PekoraOuO** [comment]
我星幻也是不過習慣了反正我射速快看不太出來，但是仔細看火光也是賊大

**Comment by cliff1o** [comment]
fixed , 可測試
