### ISSUE TITLE
【BUG】任务噩梦专家

### ISSUE THREAD

**Issue by 1132904601** [cliff1o/publicresource#329]
先接这个任务 然后再完成伤害支线任务 然后这个噩梦专家任务就会自动被放弃

**Comment by cliff1o** [comment]
![image](https://github.com/user-attachments/assets/3027af87-35b3-47fa-82a5-236a5b68eb1e)
測試服唔見有問題, 要求核心再測試 

過程有沒有見到 force reset ? 左下

**Comment by 1132904601** [comment]
测试后发现并没有问题，关闭此贴
