### ISSUE TITLE
【建议】提高一下痛枪合成经验获取途径或者经验值

### ISSUE THREAD

**Issue by 1132904601** [cliff1o/publicresource#331]
比如神化模式 挑战模式胜利可以+5
或者提高总的经验获取值
目前的我个人是每天晚上都能打到200经验值，有玩家反应太慢

**Comment by cliff1o** [comment]
慢的定義係?  要求提供數據

**Comment by 1132904601** [comment]
周一至周五 以我的标准是每天平均能获得250经验值 当前是消耗100经验可以提升0.5~1.5 那么根据经验值假设每天进度都能提升2.5%
按照平均来算100/2.5=40天能够完成。当然算上周末的时间我预估应该是刚好30天能够肝到
不知道是否达到你设计的预期时间

**Comment by cliff1o** [comment]
不接受,  9月1更新, 9月7 己有人肝出 
進度不見得慢
