### ISSUE TITLE
【建议】凖雷系改为可以打神化or降低神化出场概率

### ISSUE THREAD

**Issue by 1132904601** [cliff1o/publicresource#332]
现在神化出场概率太高了，一张地图有一半的局数是神化王，V1 凖雷完全打不了必须要另外用枪。
这样的情况下凖雷系的枪缺点太大了，如果不能改的话，也可以考虑给凖雷系的枪其他方面的加强补正

**Comment by cliff1o** [comment]
準雷設定 係激光系, 而激光系打不到神化王,    設定不會更改
後續模式會以細王為主,  平衡神化模式過多
