### ISSUE TITLE
【建议】枪械经验转移

### ISSUE THREAD

**Issue by Funnyqun** [cliff1o/publicresource#335]
个人感觉转移的价格太贵了，转一下上百万sp起步，抽到新枪还要打一个月才能凑齐，有点太久了。

**Comment by cliff1o** [comment]
不能降價, 否則會造成一把槍打經驗分給其他槍問題
價格高是提高你們想轉移的成本

**Comment by Funnyqun** [comment]
> 不能降價, 否則會造成一把槍打經驗分給其他槍問題 價格高是提高你們想轉移的成本

氪佬商城买突破卡去卖根本不缺sp，这个价格设定完全是卡平民玩家的吧。还有建议的贴为啥关这么快。

**Comment by Funnyqun** [comment]
> 不能降價, 否則會造成一把槍打經驗分給其他槍問題 價格高是提高你們想轉移的成本

一把枪打经验给其他枪，你把价格提高，氪佬又不在意，完全是在限制平民玩家，所以这个功能设计初衷就是给氪佬用的？

**Comment by Funnyqun** [comment]
> 不能降價, 否則會造成一把槍打經驗分給其他槍問題 價格高是提高你們想轉移的成本

枪械等级突破已经够卡进度的了，平民玩家就算转移了枪械经验打伤害也一样打不过氪佬，所以现在这个转移价格有什么合理性吗？
