### ISSUE TITLE
【BUG】完成痛枪充能后点击领取实际没有领取到

### ISSUE THREAD

**Issue by 1132904601** [cliff1o/publicresource#339]
![痛枪BUG](https://github.com/user-attachments/assets/0d677741-9479-4250-83be-942029b73b50)
![痛枪BUG2](https://github.com/user-attachments/assets/1836f2a7-75be-4356-87c6-87b914b0e696)
name:Furina

**Comment by cliff1o** [comment]
估計是早期 (第一日更新時) 有人在我修BUG前接了 而造成
要求核心 使用測試AC ,  用材料測試一次 

另外補回他槍械

**Comment by 1132904601** [comment]
9/8日测试
合成无效 没有获得痛枪并且AK60r原枪械还在
![痛枪1](https://github.com/user-attachments/assets/f6322fb1-c192-41cd-9c41-4449a63e8ef8)
![痛枪2](https://github.com/user-attachments/assets/f749bc85-5f97-404a-9c5f-e079a2cb43ef)
![痛枪3](https://github.com/user-attachments/assets/238393ce-4dc6-443d-a29b-bcbd04ec2933)

**Comment by cliff1o** [comment]
fixed, 可測試

**Comment by 1132904601** [comment]
![60R合成成功](https://github.com/user-attachments/assets/b5946c0b-dd58-43a2-8338-59ac2b64367e)
合成成功，但是AK60R原版枪未移除
