### ISSUE TITLE
【BUG】物品"空白"可以賣掉/扔棄

### ISSUE THREAD

**Issue by siunam321** [cliff1o/publicresource#34]
![image](https://github.com/cliff1o/publicresource/assets/104430134/e307032b-a513-4e8f-b93b-414e59e8c05f)

![image](https://github.com/cliff1o/publicresource/assets/104430134/9a1912fd-5a69-4aba-b17c-9d547ebefc4f)

**Comment by cliff1o** [comment]
cssdk_const.inc  , added item_none in 1.9.0 ,  conflict with boss enum
/**
* Constant items
*/
enum ItemID
{
	ITEM_NONE = -1,
