### ISSUE TITLE
【建议】有玩家建议增加一些新手专门的任务

### ISSUE THREAD

**Issue by 1132904601** [cliff1o/publicresource#346]
只有1500级以下才可以做
变魔王50次奖励g
用魔王一局内杀25个人奖励sp
对魔王造成50w伤害一百次奖励sp
杀魔王15次奖励sp或者g
每天在线两小时25次奖励g
当ld存活20次奖励sp

转[1x6]代填

**Comment by cliff1o** [comment]
不接受,  只會令到 1500 級問題惡化
