### ISSUE TITLE
【建议】增加新手玩家的福利

### ISSUE THREAD

**Issue by 1132904601** [cliff1o/publicresource#347]
新手专属的活动，在线一小时可以抽奖一次，奖池里面有sp g 超特 和特别枪，抽20次保底（1～3）天的超特
抽一次奖过后，下一次抽奖就要增加多一点时间，每天签到可以重置，抽奖次数到一定的数量可以领取奖励，大奖给人物 或者刀具箱子又或者t系列的。建议等级2000级以下
转[1x6]代填

**Comment by cliff1o** [comment]
不接受,  只會令到 1500 級問題惡化
