### ISSUE TITLE
【BUG】Dr.Rex 左鍵沒有傷害

### ISSUE THREAD

**Issue by siunam321** [cliff1o/publicresource#36]

**Comment by cliff1o** [comment]
for(new i = 1; i <= g_MaxPlayers; i++) <-- add to 32 + 1
	{
		if(!is_user_alive(i) || i == Owner)
			continue
			
		pev(i, pev_origin, POrigin)
		if(get_distance_f(Origin, POrigin) > REX_ATTACK_RANGE)
			continue
		


		if(realrage && is_user_connected(Owner))
		{
			ExecuteHamB(Ham_Killed, i, Owner, 0)
		}
		else
		ExecuteHamB(Ham_TakeDamage, i, 0, i, REX_ATTACK_DMG , DMG_BLAST)
		Make_PlayerShake(i)
	}
