### ISSUE TITLE
【BUG】波动攻击无视复活保护

### ISSUE THREAD

**Issue by Miyuuuko** [cliff1o/publicresource#37]

**Comment by cliff1o** [comment]
stock damage_extra(victim, attacker, damage, damage_type)
{
	if(damage_type == DMG_SONIC)
	damage = floatround( float(damage) * ( 1.0 - job_skill[victim][35] * 0.02))

	if(random_num(0, 100) > 100 - job_skill[victim][39])
	damage = 0

	if(get_user_godmode(victim)) <-- added godmode check
	damage = 0
