### ISSUE TITLE
【BUG】当双子神话王时容易判定挂机被踢出

### ISSUE THREAD

**Issue by 1132904601** [cliff1o/publicresource#38]
当双子神话王时，一直在动和杀人，但是却被系统提示在挂机，倒计时结束后就被踢出了

**Comment by cliff1o** [comment]
if((get_user_team(id) == 2 && TimeAFK[id] >= pTimeAFK / 2) || (get_user_team(id) == 1 && !get_ragemonster(id) && TimeAFK[id] >= (pTimeAFK / 2) / 2))
	{
        	set_dhudmessage(255, 255, 255, -1.0, 0.17, 0, 0.3, 0.3, 0.3, 0.3)
                if (get_user_team(id) == 1) show_dhudmessage(id, "如果您不作出行動，系統將會在 %d 秒後直接踢出。" ,(pTimeAFK / 2) - TimeAFK[id])
	        if (get_user_team(id) == 2) show_dhudmessage(id, "如果您不作出行動，系統將會在 %d 秒後直接踢出。" ,pTimeAFK - TimeAFK[id])
	}


不知什麼原因使用了AZ的掛機.    己修正
