### ISSUE TITLE
BUG JACK

### ISSUE THREAD

**Issue by xkoalaxasukax** [cliff1o/publicresource#48]
當JACK魔王沒有任何技能按鍵可以使用

**Comment by cliff1o** [comment]
fixed

**Comment by Tonylemon19** [comment]
![Z~5L~SMR74 X1UQ1%MU GD0](https://github.com/cliff1o/publicresource/assets/54575597/47e89dc0-ce14-4fa7-9282-c9f294c594bb)
又出现bug了 且根据反应似乎物理枪械攻击伤害远低于正常水平

**Comment by cliff1o** [comment]
fixed
