### ISSUE TITLE
【建议】优化结算思路

### ISSUE THREAD

**Issue by Tonylemon19** [cliff1o/publicresource#53]
鉴于目前结算有上限限制且结算方式采用类似`while( i > 1500) loop`的样式
是不是有`int count = i / 1500`类似的方法使得能够直接计算结算奖励次数的优化方式？

**Comment by cliff1o** [comment]
其中之一考慮方向.   loop 內call了不小func , 用count 要重寫好多部份判定

**Comment by cliff1o** [comment]
new added = floatround( PlayerDamage[attacker] / Damage_Num )
		PlayerDamage[attacker] -= Damage_Num * added

		if(added >= 20) added = 20

優化 , 上限20 次 防BUG
