### ISSUE TITLE
【BUG】火神机枪的枪口火焰太挡视线和晃眼了

### ISSUE THREAD

**Issue by rencc1379** [cliff1o/publicresource#6]
![QQ图片20240519141540](https://github.com/cliff1o/publicresource/assets/95602416/a7e94970-578e-4a4a-aa99-634f1f74d176)
枪口火焰太大了，又挡视线又晃眼睛...

**Comment by cliff1o** [comment]
估計在 1.4 版本

**Comment by cliff1o** [comment]
deployed
