### ISSUE TITLE
建議優化 Dr.Rex 三連擊

### ISSUE THREAD

**Issue by xkoalaxasukax** [cliff1o/publicresource#64]
使用技能針對有大型躲避物玩家時候 ，會判定在玩家天上直接往上飛 直到技能結束

**Comment by cliff1o** [comment]
唔明

**Comment by xkoalaxasukax** [comment]
![20240526073605_1](https://github.com/cliff1o/publicresource/assets/170393732/9b8026aa-98ec-49ef-bf05-86fbce83ea2c)
![20240526073611_1](https://github.com/cliff1o/publicresource/assets/170393732/851afb41-21d1-4d3f-b5fe-fe37bd641601)

**Comment by xkoalaxasukax** [comment]
一張是玩家躲的地方 一張是Dr.Rex使用三連擊後飛去的地方

**Comment by xkoalaxasukax** [comment]
我那時候剩下2個玩家都躲在那，原本要用三連擊過去結束那場 結果 我用了技能他就給我往我上面那張圖一樣朝著那個方向飛過去 而且使用了2次都是一樣的

**Comment by xkoalaxasukax** [comment]
還有一張地圖也有只是忘記地圖名 跟那個躲避物一樣類似 也會這樣

**Comment by cliff1o** [comment]
如果JACK 有沒有這問題

**Comment by xkoalaxasukax** [comment]
有，但跟Dr.Rex不一樣 會從那個躲避物下方移動 但一樣打不到人

**Comment by cliff1o** [comment]
暫時未有方法修正 , 因 dash 是用fly object 問題,  如要做到躲避物 , 是要navmesh + 大量檢查判定
現階段不可行,
