### ISSUE TITLE
BUG 每日一槍

### ISSUE THREAD

**Issue by xkoalaxasukax** [cliff1o/publicresource#67]
使用每日一槍後 後續使用武器後不小心切到小刀跟小槍 結果整個主武器無法點出來 要搞到換下張地圖才能正常點出主武器可以使用

**Comment by cliff1o** [comment]
那一把槍

**Comment by xkoalaxasukax** [comment]
每日一槍 火神機槍
後續用的特別槍 水火相容.AT4(但使用後 它的圖標判定是火神機槍那個圖標)

**Comment by cliff1o** [comment]
fixed in 1.4
