### ISSUE TITLE
卡牆事件 雙子 

### ISSUE THREAD

**Issue by xkoalaxasukax** [cliff1o/publicresource#69]
![20240526223413_1](https://github.com/cliff1o/publicresource/assets/170393732/1310764a-17d1-4b0a-94ad-7e1dcc98f0f1)

因為她當雙子時候 由於它變身階段會黑畫面 結果走著走著碰到牆壁結果變成這樣

**Comment by cliff1o** [comment]
無法修正,  變王前自己注意位置
