### ISSUE TITLE
【BUG】zh_big_lostcity 地圖異常，進去會卡在奇怪視角

### ISSUE THREAD

**Issue by Sora977** [cliff1o/publicresource#7]
![Half Life Screenshot 2024 05 19 - 16 54 45 83](https://github.com/cliff1o/publicresource/assets/87259269/aacc7a9c-3f7c-494e-a36e-a42c98d283c9)
![Half Life Screenshot 2024 05 19 - 16 54 52 67](https://github.com/cliff1o/publicresource/assets/87259269/a8f41f26-e86b-4073-9e17-b958607ee3e9)

**Comment by cliff1o** [comment]
地圖拿掉了
