### ISSUE TITLE
【BUG】職業復仇者"憤怒"後職業肌肉型"傷害爆發"無效

### ISSUE THREAD

**Issue by siunam321** [cliff1o/publicresource#71]
武器: 變異準雷v1

死亡前 (未使用"傷害爆發")
![image](https://github.com/cliff1o/publicresource/assets/104430134/58c31203-a546-4174-b000-c015e0cd3ef8)

死亡前 (使用"傷害爆發")
![image](https://github.com/cliff1o/publicresource/assets/104430134/03f763a3-de6f-4917-91ef-70a117b3da40)

死亡後 (未使用"傷害爆發")
![image](https://github.com/cliff1o/publicresource/assets/104430134/e75334e2-0470-4a89-a2ae-35baede79e26)

死亡後 (使用"傷害爆發")
![image](https://github.com/cliff1o/publicresource/assets/104430134/5f619466-a0ec-4674-86b0-7ca2f2e80c2a)

**Comment by cliff1o** [comment]
https://github.com/cliff1o/publicresource/issues/8
