### ISSUE TITLE
【BUG】魔王惡夢2/2 進化技能"升龍霸"有機會死服

### ISSUE THREAD

**Issue by siunam321** [cliff1o/publicresource#73]

**Comment by cliff1o** [comment]
static Float:Light 
			pev(ent, pev_renderamt, Light)
		
			Light -= 5.0
			Light = floatmax(Light, 0.0)
			set_pev(ent, pev_renderamt, Light)
			
			if(Light <= 0.0)
			{
				set_pev(ent, pev_flags, FL_KILLME)
				return
			}

missing renderamt
