### ISSUE TITLE
【BUG】复活后使用肌肉型职业的伤害爆发技能无效果

### ISSUE THREAD

**Issue by 1132904601** [cliff1o/publicresource#8]
复活后使用肌肉型职业的伤害爆发技能无效果，只有第一条命使用伤害爆发技能时可生效

**Comment by cliff1o** [comment]
問題 :  第一條命不用, 第二條命用有沒有效果

**Comment by 1132904601** [comment]
> 問題 : 第一條命不用, 第二條命用有沒有效果

同样没有效果，只有第一条命使用是有效的

**Comment by 1132904601** [comment]
我发现我第二个职业是复仇者，点了技能愤怒复活后1.25倍攻，肌肉型伤害爆发技能也是1.25倍攻，会不会是2者不能叠加使用。

**Comment by cliff1o** [comment]
else if(g_status[attacker] == 10 || g_respawn[attacker] && job_skill[attacker][16])
		Bs = 1.25

傷害使用了同一個判定.  
修改為同時爆發和复仇者 傷害為 1 + (25% x 25%)
