### ISSUE TITLE
【BUG】職業復仇者"憤怒"無效

### ISSUE THREAD

**Issue by siunam321** [cliff1o/publicresource#80]
武器: AT4

死亡前:

![image](https://github.com/cliff1o/publicresource/assets/104430134/d577312b-d97e-4498-8f20-d5e2f3926edc)

死亡後:

![image](https://github.com/cliff1o/publicresource/assets/104430134/d9a7612c-8630-4e80-ae55-74e4e12c7cb0)

正常死亡後攻石數值是`1.3`

**Comment by cliff1o** [comment]
else if(g_respawn[attacker] && job_skill[attacker][16] && g_status[attacker] == 10)
		Bs = 1.31
		else if(g_status[attacker] == 10 || g_respawn[attacker] && job_skill[attacker][16])
		Bs = 1.25
