### ISSUE TITLE
【BUG】滿等級重入服可獲得無限技能點

### ISSUE THREAD

**Issue by siunam321** [cliff1o/publicresource#84]
已知: 資料**未載入前**會有這個問題

資料載入前:

![image](https://github.com/cliff1o/publicresource/assets/104430134/d102d2f6-e53f-428d-94fa-95c13b0c0124)

資料載入後:

![image](https://github.com/cliff1o/publicresource/assets/104430134/84a3b6b0-f5db-44c2-be5e-3de6a842e331)

https://github.com/cliff1o/publicresource/assets/104430134/1c8c913b-af9d-496c-b7f2-20162327ad5a

**Comment by cliff1o** [comment]
fixed
