### ISSUE TITLE
【BUG】噩梦能力：伤害爆发打出来的暴击伤害没有原伤害高

### ISSUE THREAD

**Issue by Miyuuuko** [cliff1o/publicresource#85]

**Comment by siunam321** [comment]
測試後噩夢能力"傷害爆發"無效

**Comment by siunam321** [comment]
有效了:
![image](https://github.com/cliff1o/publicresource/assets/104430134/d79bb474-0b1d-413d-b930-545861648d83)

**Comment by Miyuuuko** [comment]
![QQ截图20240531160826](https://github.com/cliff1o/publicresource/assets/166730958/94949713-fd97-4f0a-8db3-816b6e526b5e)
![QQ截图20240531160957](https://github.com/cliff1o/publicresource/assets/166730958/f8a8b6c1-78b1-427c-9fb5-167c88a5f11e)
显示错误？

**Comment by siunam321** [comment]
又好像無效?

**Comment by cliff1o** [comment]
暫時見有效?

**Comment by Miyuuuko** [comment]
我用离子改没有生效过

**Comment by siunam321** [comment]
有效，但機率異常地低

**Comment by cliff1o** [comment]
暫時代碼所見是有效果
