### ISSUE TITLE
【BUG】魔王技能"波動攻擊"強化無效

### ISSUE THREAD

**Issue by siunam321** [cliff1o/publicresource#91]
![image](https://github.com/cliff1o/publicresource/assets/104430134/328d3253-a783-4825-8045-ca507dd78a37)

![image](https://github.com/cliff1o/publicresource/assets/104430134/4a9b109b-1ebc-43f5-a9cd-eb326384c23a)

`0 * x = 0`?

**Comment by cliff1o** [comment]
修改技能效果, 改為每級強化 + 次數
