### ISSUE TITLE
【建议】加强龙炮改

### ISSUE THREAD

**Issue by JOvvv1** [cliff1o/publicresource#99]
做为1500G的武器一发伤害4000+，还能打出惊人的3000，虽然说有两段伤害，但是不能100%触发，还需要近战输出，收益和风险不成正比，连普通的离子一发两颗子弹都能稳定打出5000+伤害，这居然是一把1500G的武器。

**Comment by wdf250** [comment]
同意

**Comment by cliff1o** [comment]
請提升槍械傷害,  每級100攻, 成長值是十分高
